/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_quickcan_image_watermarkdetection_component_WatermarkDetector */

#ifndef _Included_com_quickcan_image_watermarkdetection_component_WatermarkDetector
#define _Included_com_quickcan_image_watermarkdetection_component_WatermarkDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quickcan_image_watermarkdetection_component_WatermarkDetector
 * Method:    ifContainsDouyinLogo
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_quickcan_image_watermarkdetection_component_WatermarkDetector_ifContainsDouyinLogo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
